version: '3'

services:
  api:
    build:
      context: ./exchange_api
      dockerfile: Dockerfile
    ports:
      - "7050:7050"
    volumes:
      - .:/app
  bot:
    container_name: easybyte
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: always
    network_mode: host